### ISSUE TITLE
Footnotes give text a different color.

### ISSUE THREAD

**Issue by bertcoerver** [geek1011/kepubify#45] opened 2019-12-30 13:30 UTC
Hello,

I'm having the following problem when converting books, related to (references to) footnotes. 

For some of my converted books, each first footnote in a chapter causes all the preceding text in that chapter to have a different color from the default color. After the first footnote, the text has the default color and any subsequent footnotes in that chapter work as intended. 

The original epub with a footnote:

![Screenshot 2019-12-30 at 14 27 01](https://user-images.githubusercontent.com/18460767/71583903-a0795a00-2b10-11ea-8498-37ea2c9e655e.png)

The converted epub with all the text preceding the first footnote in the chapter in a different color:

![Screenshot 2019-12-30 at 14 27 39](https://user-images.githubusercontent.com/18460767/71583942-c30b7300-2b10-11ea-94d4-98e9557d5446.png)

**Comment by geek1011** [comment] 2020-01-04 20:18
I'm guessing this is due to a self-closing A tag (e.g. `<a id="footnote1" />"), which is [against the spec](https://html.spec.whatwg.org/multipage/syntax.html#void-elements), but some badly-designed books use it. When it is parsed by kepubify (or any other semi-strict parser), it parses it as an open tag only, and closes it in the last possible place.

I could add a workaround to kepubify, but that's almost outside the scope of kepubify. I'll see if the KEPUB reader accepts invalid void elements when I have time, and if it does, I'll also make kepubify do it as well.

**Comment by geek1011** [comment] 2020-01-12 04:00
This is what happens when it is parsed:

https://play.golang.org/p/2VHmxGqKm5P
```go
package main

import (
	"fmt"
	"strings"

	"github.com/PuerkitoBio/goquery"
)

func main() {
	doc, _ := goquery.NewDocumentFromReader(strings.NewReader(`<!DOCTYPE html><html><head><title></title></head><body>test 1<a id="test"/>test 2<p>test 3</p></body></html>`))
	html, _ := doc.Html()
	fmt.Println(html)
}

// output: <!DOCTYPE html><html><head><title></title></head><body>test 1<a id="test">test 2<p>test 3</p></a></body></html>
```

I'm going to test it with the KEPUB renderer now.

**Comment by geek1011** [comment] 2020-01-12 04:29
I won't be fixing this issue immediately, as it requires restructuring how the parsing is done.

The issue is that kepubify always parses the HTML as HTML5, which means it follows HTML5 parsing rules, namely about treating self-closing tags which aren't void elements as if the closing doesn't exist (see https://html.spec.whatwg.org/multipage/parsing.html#parse-error-non-void-html-element-start-tag-with-trailing-solidus). The KEPUB renderer either parses it according to the DOCTYPE or always as XHTML (I haven't checked yet).

To fix this problem, I have a few options:
- Fork golang.org/x/net/html and allow self-closing `a` tags by not ignoring the `/`. This would also allow me to remove the ugly workaround for self-closing `title` tags.
- Parse everything as XHTML. This is probably the least optimal solution, as it would prevent me from using goquery, and would also break proper HTML5 books, which are a lot more common.
- Parse everything according to the DOCTYPE. This would work, but would result in either a lot of code duplication or a lot of abstraction (or embedding a C library like lxml, which I'd rather not do).
- Fix this specific case with a regexp. I'd rather not add any more regexp-hacks to kepubify, as there are already enough as it is.

I'm most likely going to do either the first or the fourth option. I'll probably leave it for the next version, though, and improve the whole content manipulation code while I'm at it.

**Closed** 2020-01-14 23:30 UTC
Labels: bug, epub issue
